### ISSUE TITLE
Goal setting feature

### ISSUE THREAD

**Issue by NataliiaRemezova** [justingebert/b4-hypnobuddy#27]
An epic for the goal setting feature

- [ ] As a user, I want to have a possibility to set my goals in the app.
- [ ] As a user, I want to be able to track my progress towards my goal.
- [ ] As a user, I want to break my big goal into smaller steps, to have a plan of achieving it.
- [ ] As a user, I want to get rewards for competing steps towards my goal.
